# MAGI Review 설정
version: 1

# Provider 설정
provider:
  type: gemini

# 투표 설정
voting:
  required_approvals: 2

# 토론 기능 (Phase 2)
debate:
  enabled: false

# 출력 설정
output:
  pr_comment:
    enabled: true
    style: detailed
  labels:
    enabled: true
